version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    # Publish HTTP and HTTPS from container to host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./www:/var/www/certbot:ro
    networks:
      - app-network
    # Always restart unless manually stopped
    restart: unless-stopped

  certbot:
    build:
      context: .
      dockerfile: ./docker/certbot/Dockerfile
    volumes:
      - ./certs:/etc/letsencrypt/live
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/certbot
    depends_on:
      - web
    networks:
      - app-network
    command: certonly --webroot -w /var/www/certbot --email speeebot@gmail.com --agree-tos --no-eff-email -d shawndiaz.dev -d www.shawndiaz.dev --force-renewal --non-interactive
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
